# 테스트용 설정
# Entity에 맞게 테이블을 새로 만들지만
# 테스트용 데이터를 사용하지 않고
# 실제로 파일로 저장하는 DB가 아닌 H2 in-memory DB 사용
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never